name: Deploy

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: wcmchenry3-stack/book_app/.github/workflows/ci.yml@a973bcce934fef46e22d40123430ad2594d5bada
    secrets: inherit

  deploy:
    needs: ci
    uses: wcmchenry3-stack/.github/.github/workflows/called-deploy-render.yml@a973bcce934fef46e22d40123430ad2594d5bada
    with:
      service-name: 'bookshelf-api'
      service-id: 'srv-d6vkel7fte5s73du7fc0'
      zap-target-url: 'https://bookshelf-api-rxp3.onrender.com'
    secrets: inherit
